#!/bin/sh
set -e # fail on errors

# Redirect stderr -> stdout
exec 2>&1



cd /var/opt/gitlab/gitlab-workhorse

exec chpst -e /opt/gitlab/etc/gitlab-workhorse/env -P \
  -U git:git \
  -u git:git \
  /opt/gitlab/embedded/bin/gitlab-workhorse \
    -listenNetwork unix \
    -listenUmask 0 \
    -listenAddr /var/opt/gitlab/gitlab-workhorse/socket \
    -authBackend http://localhost:8080 \
    -authSocket /var/opt/gitlab/gitlab-rails/sockets/gitlab.socket \
    -documentRoot /opt/gitlab/embedded/service/gitlab-rails/public \
    -pprofListenAddr ''\
    -prometheusListenAddr localhost:9229 \
    -secretPath /opt/gitlab/embedded/service/gitlab-rails/.gitlab_workhorse_secret \
    -logFormat json \
    -config config.toml \

# Do not remove this line; it prevents trouble with the trailing backslashes above.
