#!/bin/sh

cd /var/opt/gitlab/gitlab-rails/working

exec 2>&1
# Setup run directory.
mkdir -p /run/gitlab/sidekiq
rm /run/gitlab/sidekiq/*.db 2> /dev/null
chmod 0700 /run/gitlab/sidekiq
chown git /run/gitlab/sidekiq
export prometheus_run_dir='/run/gitlab/sidekiq'



exec chpst -e /opt/gitlab/etc/gitlab-rails/env -P \
  -U git:git \
  -u git:git \
  /usr/bin/env \
    prometheus_multiproc_dir="${prometheus_run_dir}" \
    /opt/gitlab/embedded/bin/bundle exec sidekiq \
      -C /opt/gitlab/embedded/service/gitlab-rails/config/sidekiq_queues.yml \
      -e production \
      -r /opt/gitlab/embedded/service/gitlab-rails \
      -t 4 \
      -c 25
