#!/bin/sh

# Attempt to change ulimit before the set -e flag, ignore failures
ulimit -n 15000

set -e # fail on errors

# Redirect stderr -> stdout
exec 2>&1



cd /var/opt/gitlab/gitaly

exec chpst -e /opt/gitlab/etc/gitaly/env -P \
  -U git:git \
  -u git:git \
  /opt/gitlab/embedded/bin/gitaly-wrapper /opt/gitlab/embedded/bin/gitaly /var/opt/gitlab/gitaly/config.toml
