#!/bin/sh
exec 2>&1


cd '/var/opt/gitlab/grafana'

umask 077
exec chpst -P -e /opt/gitlab/etc/grafana/env \
  -U gitlab-prometheus:gitlab-prometheus \
  -u gitlab-prometheus:gitlab-prometheus \
  /opt/gitlab/embedded/bin/grafana-server -config '/var/opt/gitlab/grafana/grafana.ini'
